### PR TITLE
fix: Added 3 goals

### PR DESCRIPTION
**Pull request by HanaHy**

### CODE REVIEW

**Comment by edwann13** [comment]
@HanaHy when creating the steps should the add more steps button work?
and what order should My Completed Tasks be arranged in? from newest to oldest or backwards?

**Comment by HanaHy** [comment]
As of now I've decided not to add that in, should I just remove the add steps part?

**Comment by edwann13** [comment]
@HanaHy hmm can't we comment it out for now until the functionality is placed?

**Comment by HanaHy** [comment]
Just did that! :-)

**Pull request merged**
